seo:
  main-tagline: A collection of writings

index:
  catch-line: And this is my website. I tell stories. I make videos. I believe that great power lies using your voice. We all have a story to tell and this is mine.

about:
  life-with-gutz: Life with Gutz is my adventure online. A place where I explore building a personal brand and using my voice amid the cacophony online. Personal Brand? It's cringey AF to say, but the internet is a great equalizer. It's my entrepreneurial adventure, and I don't know exactly where it's headed yet, but I plan on documenting the journey. In a world on fire that chews up people as nothing more than 'human capital,' I thought I'd start creating my own opportunities that don't harm and maybe even help...and I'm going to have fun doing it.
  katie: Also known as Kate, Kathleen, and Gutz (pronounced Gootz), is an award-winning video professional with over a decade of experience. Her work has been seen on CBC's Doczone and various national outlets in her capacity as a video director and editor for The War Amps of Canada. Check out her <a href="https://www.linkedin.com/in/kathleengutzman/">LinkedIn</a> for a full list of credits and awards. When she's not creating videos, she's playing with fire or exploring another of her many artistic outlets. Always curious with a focus on growth, this life is meant to be lived.

contact:
  title: Let's connect!
  para: Want to connect, collab, or just say hey? Need a story told? Fancy a distanced fire or LED performance? Rock on. Get in touch below and let's talk!
