socials:
  facebook: "https://www.facebook.com/lifewithgutz"
  instagram: "https://www.instagram.com/lifewithgutz/"
  youtube: "https://www.youtube.com/KatieGutz"
  twitter: "https://twitter.com/KatieGutz"
  tiktok: "https://www.tiktok.com/@lifewithgutz"
  pinterest: "https://www.pinterest.ca/LifewithGutz/"
  twitch: "https://www.twitch.tv/lifewithgutz"
  linked-in: "https://www.linkedin.com/in/kathleengutzman/"
