backend:
  name: github
  repo: Life-with-Gutz/main-site-2020
  branch: master

media_folder: "images/uploads"

collections:
  - name: "content-editor"
    label: "General Settings"
    files:
      - label: "General Settings"
        name: "site"
        file: "_data/site.yml"
        fields:
          - label: "Socials"
            name: "socials"
            widget: "object"
            hint: "This content is available if you wish to update your social handles, however it is likely that you will not need to alter any of the data on this page."
            fields:
              - label: "Facebook Handle"
                name: "facebook"
                widget: "string"
              - label: "Instagram Handle"
                name: "instagram"
                widget: "string"
              - label: "Youtube Handle"
                name: "youtube"
                widget: "string"
              - label: "Twitter Handle"
                name: "twitter"
                widget: "string"
              - label: "Tiktok Handle"
                name: "tiktok"
                widget: "string"
              - label: "Pinterest Handle"
                name: "pinterest"
                widget: "string"
              - label: "Twitch Handle"
                name: "twitch"
                widget: "string"
              - label: "LinkedIn Handle"
                name: "linked-in"
                widget: "string"
  - name: "pages"
    label: "Pages"
    files:
      - label: "Homepage"
        name: "home"
        file: "_data/index.yml"
        fields:
          - label: "Homepage"
            name: "index"
            widget: "object"
            fields:
              - label: "Banner Image"
                name: "banner-image"
                widget: "image"
              - label: "Welcome Line"
                name: "welcome-line"
                widget: "string"
                hint: Be careful about changing this from the word "WELCOME", it could compromise the design.
              - label: "Tagline"
                name: "tagline"
                widget: "string"
                hint: Copy that follows the declaration "I'm Gutz" that is right under the main banner.
          - label: "SEO"
            name: "seo"
            widget: "object"
            fields:
              - label: "Metadata Page Description"
                name: "meta"
                widget: "string"
              - label: "Keywords"
                name: "keywords"
                widget: "string"
                hint: Separate your keywords by a comma and space.
      - label: "About"
        name: "about"
        file: "_data/about.yml"
        fields:
          - label: "About"
            name: "about"
            widget: "object"
            fields:
              - label: "About Life with Gutz"
                name: "life-with-gutz"
                widget: "markdown"
              - label: "Life with Gutz Image"
                name: "image-gutz"
                widget: "image"
              - label: "Life with Gutz Image Alt Text"
                name: "alt-gutz"
                widget: "string"
                hint: "This text will display if for some reason a user's browser cannot display images."
              - label: "About Katie"
                name: "katie"
                widget: "markdown"
              - label: "Katie Image"
                name: "image-katie"
                widget: "image"
              - label: "Katie Image Alt Text"
                name: "alt-katie"
                widget: "string"
                hint: "This text will display if for some reason a user's browser cannot display images."
          - label: "SEO"
            name: "seo"
            widget: "object"
            fields:
              - label: "Metadata Page Description"
                name: "meta"
                widget: "string"
              - label: "Keywords"
                name: "keywords"
                widget: "string"
                hint: Separate your keywords by a comma and space.
      - label: "Contact"
        name: "contact"
        file: "_data/contact.yml"
        fields:
          - label: "Contact"
            name: "contact"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Paragraph"
                name: "para"
                widget: "string"
              - label: "Image"
                name: "image"
                widget: "image"
              - label: "Image Alt Text"
                name: "alt"
                widget: "string"
                hint: "This text will display if for some reason a user's browser cannot display images."
          - label: "SEO"
            name: "seo"
            widget: "object"
            fields:
              - label: "Metadata Page Description"
                name: "meta"
                widget: "string"
              - label: "Keywords"
                name: "keywords"
                widget: "string"
                hint: Separate your keywords by a comma and space.
      - label: "Multi-Page Elements"
        name: "multi"
        file: "_data/multi.yml"
        fields:
          - label: "Emailer"
            name: "email"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Paragraph"
                name: "para"
                widget: "markdown"
              - label: "Call Out"
                name: "callout"
                widget: "string"
              - label: "Image"
                name: "image"
                widget: "image"
              - label: "Image Alt Text"
                name: "alt"
                widget: "string"
                hint: "This text will display if for some reason a user's browser cannot display images."
  - name: "blog-posts"
    label: "Blog Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "post"
      - label: "Image"
        name: "img"
        widget: "image"
      - label: "Image Alt Text"
        name: "img-alt"
        widget: "string"
        hint: "This text will display if for some reason a user's browser cannot display images."
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Date"
        name: "write-date"
        widget: "string"
      - label: "Categories"
        name: "categories"
        widget: "string"
        hint: "Category options, to be written exactly as follows: freelance&entrepreneurship | growth&goodlife | art&movement | storytelling. Separate category names by a single space."
      - label: "Youtube Link"
        name: "youtube"
        widget: "string"
        hint: "If you have made a youtube video that reflects the same content as this post, you can put the url link here and a button that leads the reader right to the video will appear on the page."
        required: false
      - label: "Body"
        name: "body"
        widget: "markdown"
      - label: "SEO"
        name: "seo"
        widget: "object"
        fields:
          - label: "Metadata Page Description"
            name: "meta"
            widget: "string"
            hint: This description will not show up on your site, but is a unique description of this specific page that is readable to machines and will make it easier to find your page in searches.
          - label: "Keywords"
            name: "keywords"
            widget: "string"
            hint: Separate your keywords by a comma and space.
