backend:
  name: github
  repo: life-with-gutz/main-site-2020

media_folder: "images/uploads"

collections:
  - name: "website-settings"
    label: "Website Settings"
    files:
      - label: "General Settings"
        name: "site"
        file: "_data/site.yml"
        fields:
          - label: "Main Tagline"
            name: "main-tagline"
            widget: "string"
  - name: "pages"
    label: "Pages"
    files:
      - label: "Homepage"
        name: "home"
        file: "_data/home.yml"
        fields:
          - label: "Homepage"
            name: "index"
            widget: "object"
            fields:
              - label: "Banner Image"
                name: "banner-image"
                widget: "image"
              - label: "Tagline"
                name: "tagline"
                widget: "string"
      - label: "About"
        name: "about"
        file: "_data/about.yml"
        fields:
          - label: "About"
            name: "about"
            widget: "object"
            fields:
              - label: "About Life with Gutz"
                name: "life-with-gutz"
                widget: "string"
              - label: "About Katie"
                name: "katie"
                widget: "string"
      - label: "Contact"
        name: "contact"
        file: "_data/about.yml"
        fields:
          - label: "Contact"
            name: "contact"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Paragraph"
                name: "para"
                widget: "string"
